// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEy5pMqw9l230Nu3OavUyPwgVap6nEDtQ',
    appId: '1:789026178813:web:234c8fd27ddd69d07f2094',
    messagingSenderId: '789026178813',
    projectId: 'dekoda9-30257',
    authDomain: 'dekoda9-30257.firebaseapp.com',
    storageBucket: 'dekoda9-30257.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9bO7iTw0MMBPh81zJCgmro5L1dNXfBDs',
    appId: '1:789026178813:android:e5e7947c8f4fb8887f2094',
    messagingSenderId: '789026178813',
    projectId: 'dekoda9-30257',
    storageBucket: 'dekoda9-30257.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtUOlBnwzmzAPS1efKhnI7z-_PeM0DZtk',
    appId: '1:789026178813:ios:68a1204e6937d3ce7f2094',
    messagingSenderId: '789026178813',
    projectId: 'dekoda9-30257',
    storageBucket: 'dekoda9-30257.appspot.com',
    iosClientId: '789026178813-0b9l2m8qalduttiav6h3pl46ci8q5i3h.apps.googleusercontent.com',
    iosBundleId: 'com.example.dekoda9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtUOlBnwzmzAPS1efKhnI7z-_PeM0DZtk',
    appId: '1:789026178813:ios:68a1204e6937d3ce7f2094',
    messagingSenderId: '789026178813',
    projectId: 'dekoda9-30257',
    storageBucket: 'dekoda9-30257.appspot.com',
    iosClientId: '789026178813-0b9l2m8qalduttiav6h3pl46ci8q5i3h.apps.googleusercontent.com',
    iosBundleId: 'com.example.dekoda9',
  );
}
